spring.application.name=store-service

spring.datasource.url=jdbc:postgresql://localhost:5432/storeservicedb
spring.datasource.username=postgres
spring.datasource.password=Bg053104!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
